2022-03-08 21:24:02,026 INFO    MainThread:17424 [internal.py:wandb_internal():90] W&B internal server running at pid: 17424, started at: 2022-03-08 21:24:02.025314
2022-03-08 21:24:02,027 DEBUG   HandlerThread:17424 [handler.py:handle_request():130] handle_request: run_start
2022-03-08 21:24:02,028 INFO    WriterThread:17424 [datastore.py:open_for_write():77] open: C:\Users\PC\Desktop\Wave-Defense-Learning-Environment\wandb\offline-run-20220308_212401-2ctvat3t\run-2ctvat3t.wandb
2022-03-08 21:24:03,132 DEBUG   HandlerThread:17424 [meta.py:__init__():40] meta init
2022-03-08 21:24:03,132 DEBUG   HandlerThread:17424 [meta.py:__init__():54] meta init done
2022-03-08 21:24:03,144 DEBUG   HandlerThread:17424 [meta.py:probe():214] probe
2022-03-08 21:24:03,172 DEBUG   HandlerThread:17424 [meta.py:_setup_git():204] setup git
2022-03-08 21:24:03,234 DEBUG   HandlerThread:17424 [meta.py:_setup_git():211] setup git done
2022-03-08 21:24:03,234 DEBUG   HandlerThread:17424 [meta.py:_save_pip():58] save pip
2022-03-08 21:24:03,234 DEBUG   HandlerThread:17424 [meta.py:_save_pip():72] save pip done
2022-03-08 21:24:03,234 DEBUG   HandlerThread:17424 [meta.py:_save_conda():79] save conda
2022-03-08 21:24:05,313 DEBUG   HandlerThread:17424 [meta.py:_save_conda():89] save conda done
2022-03-08 21:24:05,313 DEBUG   HandlerThread:17424 [meta.py:probe():252] probe done
2022-03-08 21:24:11,108 WARNING MainThread:17424 [internal.py:is_dead():367] Internal process exiting, parent pid 14252 disappeared
2022-03-08 21:24:11,108 ERROR   MainThread:17424 [internal.py:wandb_internal():142] Internal process shutdown.
2022-03-08 21:24:11,108 INFO    SenderThread:17424 [sender.py:finish():1070] shutting down sender
2022-03-08 21:24:11,395 INFO    WriterThread:17424 [datastore.py:close():281] close: C:\Users\PC\Desktop\Wave-Defense-Learning-Environment\wandb\offline-run-20220308_212401-2ctvat3t\run-2ctvat3t.wandb
2022-03-08 21:24:11,395 INFO    HandlerThread:17424 [handler.py:finish():731] shutting down handler
2022-03-08 21:24:11,395 INFO    MainThread:17424 [internal.py:handle_exit():77] Internal process exited
