2022-03-08 21:22:18,920 INFO    MainThread:11368 [internal.py:wandb_internal():90] W&B internal server running at pid: 11368, started at: 2022-03-08 21:22:18.919796
2022-03-08 21:22:18,921 INFO    WriterThread:11368 [datastore.py:open_for_write():77] open: C:\Users\PC\Desktop\Wave-Defense-Learning-Environment\wandb\offline-run-20220308_212217-1kkz4evp\run-1kkz4evp.wandb
2022-03-08 21:22:18,922 DEBUG   HandlerThread:11368 [handler.py:handle_request():130] handle_request: run_start
2022-03-08 21:22:19,990 DEBUG   HandlerThread:11368 [meta.py:__init__():40] meta init
2022-03-08 21:22:19,990 DEBUG   HandlerThread:11368 [meta.py:__init__():54] meta init done
2022-03-08 21:22:19,990 DEBUG   HandlerThread:11368 [meta.py:probe():214] probe
2022-03-08 21:22:20,024 DEBUG   HandlerThread:11368 [meta.py:_setup_git():204] setup git
2022-03-08 21:22:20,087 DEBUG   HandlerThread:11368 [meta.py:_setup_git():211] setup git done
2022-03-08 21:22:20,087 DEBUG   HandlerThread:11368 [meta.py:_save_pip():58] save pip
2022-03-08 21:22:20,088 DEBUG   HandlerThread:11368 [meta.py:_save_pip():72] save pip done
2022-03-08 21:22:20,088 DEBUG   HandlerThread:11368 [meta.py:_save_conda():79] save conda
2022-03-08 21:22:22,324 DEBUG   HandlerThread:11368 [meta.py:_save_conda():89] save conda done
2022-03-08 21:22:22,324 DEBUG   HandlerThread:11368 [meta.py:probe():252] probe done
2022-03-08 21:22:28,000 WARNING MainThread:11368 [internal.py:is_dead():367] Internal process exiting, parent pid 2288 disappeared
2022-03-08 21:22:28,000 ERROR   MainThread:11368 [internal.py:wandb_internal():142] Internal process shutdown.
2022-03-08 21:22:28,374 INFO    WriterThread:11368 [datastore.py:close():281] close: C:\Users\PC\Desktop\Wave-Defense-Learning-Environment\wandb\offline-run-20220308_212217-1kkz4evp\run-1kkz4evp.wandb
2022-03-08 21:22:28,374 INFO    HandlerThread:11368 [handler.py:finish():731] shutting down handler
2022-03-08 21:22:29,007 INFO    SenderThread:11368 [sender.py:finish():1070] shutting down sender
2022-03-08 21:22:29,007 INFO    MainThread:11368 [internal.py:handle_exit():77] Internal process exited
